services:
    server:
        build:
            context: ./unit_service
            dockerfile: Dockerfile
        ports:
          - "8080:8080"
        networks:
          - monitoring
    prometheus:
      image: prom/prometheus:latest
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      networks:
        - monitoring
    grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      networks:
        - monitoring

networks:
  monitoring:
    driver: bridge
